version: '3.8'

services:
  # LocalStack für AWS Services (DynamoDB, SNS, SQS, etc.)
  localstack:
    image: localstack/localstack
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - "4566:4566"  # LocalStack main port
      - "8000:4566"  # DynamoDB port mapping für compatibility
    environment:
      - SERVICES=dynamodb,sns,sqs,s3,lambda
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - microservices-network

  # Product Service
  product-service:
    build:
      context: ./app/services/product_service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - localstack
    networks:
      - microservices-network
    restart: unless-stopped

  # User Service
  user-service:
    build:
      context: ./app/services/user_service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - JWT_SECRET=myVerySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong
      - JWT_EXPIRATION=86400000
    depends_on:
      - localstack
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  localstack-data: 