global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Checkout Service
  - job_name: 'checkout-service'
    static_configs:
      - targets: ['checkout-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NGINX API Gateway
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # LocalStack
  - job_name: 'localstack'
    static_configs:
      - targets: ['localstack:4566']
    metrics_path: '/_localstack/health'
    scrape_interval: 60s 