groups:
  - name: high-availability-recording-rules
    interval: 30s
    rules:
      # Service Health Recording Rules
      - record: service:up:rate5m
        expr: avg_over_time(up[5m])

      - record: service:request_rate:rate5m
        expr: sum(rate(http_requests_total[5m])) by (service, job)

      - record: service:error_rate:rate5m
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (service, job) / sum(rate(http_requests_total[5m])) by (service, job)

      - record: service:response_time:p95:rate5m
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service, job))

      - record: service:response_time:p99:rate5m
        expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service, job))

      # System Resource Recording Rules
      - record: node:cpu_utilization:rate5m
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

      - record: node:memory_utilization:rate5m
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100

      # Load Test Recording Rules
      - record: loadtest:requests_per_second:rate1m
        expr: rate(load_test_requests_total[1m])

      - record: loadtest:response_time:p95:rate1m
        expr: histogram_quantile(0.95, rate(load_test_response_time_bucket[1m]))

      - record: loadtest:error_rate:rate1m
        expr: rate(load_test_errors_total[1m]) / rate(load_test_requests_total[1m])

      # Chaos Engineering Recording Rules
      - record: chaos:experiment_rate:rate5m
        expr: rate(chaos_experiments_total[5m])

      - record: chaos:impact_level:avg5m
        expr: avg_over_time(chaos_impact_level[5m])

      - record: chaos:circuit_breaker_triggered:rate5m
        expr: rate(circuit_breaker_triggered_total[5m])

      - record: chaos:recovery_attempts:rate5m
        expr: rate(auto_recovery_attempts_total[5m])

  # Circuit Breaker Recording Rules
  - name: circuit-breaker-recording-rules
    interval: 30s
    rules:
      # Resilience4j Circuit Breaker Metrics (Spring Boot services)
      - record: circuitbreaker:requests:rate5m
        expr: sum(rate(resilience4j_circuitbreaker_calls_total[5m])) by (name, service, target_service)

      - record: circuitbreaker:failures:rate5m
        expr: sum(rate(resilience4j_circuitbreaker_calls_total{kind="failed"}[5m])) by (name, service, target_service)

      - record: circuitbreaker:success:rate5m
        expr: sum(rate(resilience4j_circuitbreaker_calls_total{kind="successful"}[5m])) by (name, service, target_service)

      - record: circuitbreaker:failure_rate:rate5m
        expr: circuitbreaker:failures:rate5m / circuitbreaker:requests:rate5m

      - record: circuitbreaker:state_changes:rate5m
        expr: sum(rate(resilience4j_circuitbreaker_state_transitions_total[5m])) by (name, service, target_service)

      # Go Circuit Breaker Metrics (Go services)
      - record: gobreaker:requests:rate5m
        expr: sum(rate(gobreaker_requests_total[5m])) by (name, service, target_service)

      - record: gobreaker:failures:rate5m
        expr: sum(rate(gobreaker_failures_total[5m])) by (name, service, target_service)

      - record: gobreaker:success:rate5m
        expr: sum(rate(gobreaker_successes_total[5m])) by (name, service, target_service)

      - record: gobreaker:failure_rate:rate5m
        expr: gobreaker:failures:rate5m / gobreaker:requests:rate5m

      - record: gobreaker:state_changes:rate5m
        expr: sum(rate(gobreaker_state_transitions_total[5m])) by (name, service, target_service)

      # Combined Circuit Breaker Metrics (both types)
      - record: cb:total_requests:rate5m
        expr: |
          (circuitbreaker:requests:rate5m or vector(0)) + 
          (gobreaker:requests:rate5m or vector(0))

      - record: cb:total_failures:rate5m
        expr: |
          (circuitbreaker:failures:rate5m or vector(0)) + 
          (gobreaker:failures:rate5m or vector(0))

      - record: cb:overall_failure_rate:rate5m
        expr: cb:total_failures:rate5m / cb:total_requests:rate5m

      # Circuit Breaker State Indicators
      - record: cb:open_state:current
        expr: |
          (resilience4j_circuitbreaker_state{state="open"} or vector(0)) +
          (gobreaker_state{state="open"} or vector(0))

      - record: cb:half_open_state:current
        expr: |
          (resilience4j_circuitbreaker_state{state="half_open"} or vector(0)) +
          (gobreaker_state{state="half_open"} or vector(0))

      - record: cb:closed_state:current
        expr: |
          (resilience4j_circuitbreaker_state{state="closed"} or vector(0)) +
          (gobreaker_state{state="closed"} or vector(0))

  - name: aggregated-metrics
    interval: 60s
    rules:
      # Overall System Health
      - record: system:health_score:avg
        expr: avg(service_health_score)

      - record: system:service_count:up
        expr: count(up{job=~".*-service"} == 1)

      - record: system:service_count:down
        expr: count(up{job=~".*-service"} == 0)

      # Overall Request Statistics
      - record: system:request_rate:sum
        expr: sum(service:request_rate:rate5m)

      - record: system:error_rate:avg
        expr: avg(service:error_rate:rate5m)

      - record: system:response_time:p95:max
        expr: max(service:response_time:p95:rate5m)

      # Resource Utilization Aggregates
      - record: cluster:cpu_utilization:avg
        expr: avg(node:cpu_utilization:rate5m)

      - record: cluster:memory_utilization:avg
        expr: avg(node:memory_utilization:rate5m)

      # Circuit Breaker Aggregates
      - record: system:circuit_breakers:open_count
        expr: sum(cb:open_state:current)

      - record: system:circuit_breakers:total_failure_rate
        expr: avg(cb:overall_failure_rate:rate5m)

      - record: system:circuit_breakers:state_changes_rate
        expr: sum(circuitbreaker:state_changes:rate5m) + sum(gobreaker:state_changes:rate5m)

  - name: slo-metrics
    interval: 60s
    rules:
      # Service Level Objectives
      - record: slo:availability:7d
        expr: avg_over_time(service:up:rate5m[7d])

      - record: slo:error_rate:7d
        expr: avg_over_time(service:error_rate:rate5m[7d])

      - record: slo:response_time:p95:7d
        expr: quantile_over_time(0.95, service:response_time:p95:rate5m[7d])

      # Resilience Metrics - Enhanced with Circuit Breaker
      - record: resilience:recovery_success_rate:rate1h
        expr: rate(auto_recovery_success_total[1h]) / rate(auto_recovery_attempts_total[1h])

      - record: resilience:circuit_breaker_effectiveness:7d
        expr: |
          1 - (
            avg_over_time(cb:overall_failure_rate:rate5m[7d]) / 
            avg_over_time(service:error_rate:rate5m[7d])
          )

      - record: resilience:system_stability:7d
        expr: 1 - avg_over_time(system:circuit_breakers:open_count[7d]) / count(up{job=~".*-service"}) 