apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: busybox:1.35
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "🚀 Load Generator Ready!"
          echo "To start load test, exec into this pod and run:"
          echo "while true; do wget -q -O- http://product-service-demo; done"
          sleep 3600
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  labels:
    app: cpu-stress-test
spec:
  containers:
  - name: cpu-stress
    image: progrium/stress
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "🔥 CPU Stress Test Pod Ready!"
      echo "To stress test the service and trigger HPA scaling:"
      echo "stress --cpu 1 --timeout 300s"
      sleep 3600
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "200m" 