apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: production
  labels:
    app: localstack
    environment: production
    tier: infrastructure
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
        environment: production
        tier: infrastructure
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:3.5.0
        ports:
        - containerPort: 4566
          name: localstack
        env:
        - name: SERVICES
          value: "dynamodb,sns,sqs,s3,lambda,apigateway,iam,cloudwatch"
        - name: DEBUG
          value: "0"
        - name: DATA_DIR
          value: "/var/lib/localstack"
        - name: PERSISTENCE
          value: "1"
        - name: EAGER_SERVICE_LOADING
          value: "1"
        - name: LOCALSTACK_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: localstack-auth-token
              optional: true
        volumeMounts:
        - name: localstack-data
          mountPath: /var/lib/localstack
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
      volumes:
      - name: localstack-data
        persistentVolumeClaim:
          claimName: localstack-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: production
  labels:
    app: localstack
    environment: production
spec:
  ports:
  - port: 4566
    targetPort: 4566
    protocol: TCP
    name: localstack
  selector:
    app: localstack
  type: ClusterIP 