# Storage Classes for different performance tiers
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  labels:
    environment: production
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-storage
  labels:
    environment: production
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# PostgreSQL Primary Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-data
  namespace: production
  labels:
    app: postgres
    role: primary
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi
---
# PostgreSQL Backup Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-data
  namespace: production
  labels:
    app: postgres
    role: backup
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-storage
  resources:
    requests:
      storage: 100Gi
---
# Redis Data Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: production
  labels:
    app: redis
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 20Gi
---
# LocalStack Data Storage (for development/testing in production)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-data
  namespace: production
  labels:
    app: localstack
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-storage
  resources:
    requests:
      storage: 10Gi
---
# Prometheus Data Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: production
  labels:
    app: prometheus
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi
---
# Grafana Data Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: production
  labels:
    app: grafana
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-storage
  resources:
    requests:
      storage: 10Gi 