receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  # Send traces to Jaeger via HTTP OTLP  
  otlphttp:
    endpoint: http://jaeger:14268/api/traces
    
  # Logging for debugging
  logging:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, logging]

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133 