package com.product.event

enum class ProductEventType {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_INVENTORY_LOW,
    PRODUCT_INVENTORY_RESTOCKED,
    PRODUCT_PRICE_CHANGED,
    PRODUCT_CATEGORY_CHANGED
} 