# Jaeger configuration for High-Availability Architecture Demo
version: '3.8'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - QUERY_BASE_PATH=/jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Jaeger collector HTTP
      - "14250:14250"   # Jaeger collector gRPC
      - "14269:14269"   # Jaeger admin port
      - "9411:9411"     # Zipkin collector
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    command: [
      "--memory.max-traces=10000",
      "--query.max-clock-skew-adjustment=1s",
      "--query.ui-config=/etc/jaeger/ui-config.json",
      "--collector.otlp.grpc.host-port=0.0.0.0:4317",
      "--collector.otlp.http.host-port=0.0.0.0:4318",
      "--prometheus.server-url=http://prometheus:9090",
      "--prometheus.query.support-spanmetrics-connector=true",
      "--query.log-level=debug"
    ]
    volumes:
      - ./ui-config.json:/etc/jaeger/ui-config.json:ro
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    external: true 